name: CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies (root)
        run: npm install
      - name: Install dependencies (packages)
        run: npm install --workspaces
      - name: Build packages
        run: npm run build --workspaces
      - name: Test packages
        run: npm test --workspaces